directories:
  - /data/nginx/conf.d
  - /data/nginx/includes
  - /data/nginx/logs
  - /data/nginx/upstreams
  - /data/nginx/templates

ports:
  - 80:80

volumes:
  - /data/nginx/conf.d:/etc/nginx/conf.d
  - /data/nginx/includes:/etc/nginx/includes
  - /data/nginx/logs:/etc/nginx/logs
  - /data/nginx/upstreams:/etc/nginx/upstreams
  - /data/nginx/templates:/etc/nginx/templates

files: [
    {src: 'services.conf', dest: '/data/nginx/conf.d/services.conf'}
]

