- name: CentOs files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [docker]

- name: CentOs package is installed
  yum:
    name: docker-engine
    state: present
  tags: [docker]

- name: CentOs Daemon is reloaded
  command: systemctl daemon-reload
  tags: [docker]

- name: CentOs service is runnning
  service:
    name: docker
    state: running
  tags: [docker]
