- hosts: swarm
  remote_user: ubuntu
  serial: 1
  vars: 
    - debian_version: wily
    - docker_cfg_dest: /lib/systemd/system/docker.service
    - is_systemd: true
    - skip_ui: true
  roles:
    - common
    - docker
    - consul
    - swarm
    - registrator
